services:
  api-gateway:
    build: ./services/api-gateway
    container_name: kubelite-api-gateway
    ports:
      - "5000:5000"

  calculator-service:
    build: ./services/calculator-service
    container_name: kubelite-calculator-service
    ports:
      - "5001:5000"

  message-service:
    build: ./services/message-service
    container_name: kubelite-message-service
    ports:
      - "5002:5000"